# Generated by Django 3.2.8 on 2021-10-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Пациент'), ('DOCTOR', 'Врач')], default='PATIENT', max_length=100, verbose_name='Роль'),
        ),
    ]
